"""make name columns unique

Revision ID: 42072533e570
Revises: eda8dac2dc4e
Create Date: 2021-09-06 22:15:23.217326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42072533e570'
down_revision = 'eda8dac2dc4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
