name: Generate OpenAPI doc
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    container: python:3.8-buster
    steps:
      - uses: actions/checkout@master
      - name: Setup Python Libraries
        run: |
          pip3 install pipenv
          pipenv install --system
      - name: build
        run: |
          python3 -c "import json; from app.main import app; print(json.dumps(app.openapi(), indent=2))" > docs/swagger/openapi.json
      - name: save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: API doc
          path: |
            docs/swagger
